-- =======================================================
-- SCRIPT DE CONFIGURAÇÃO AUTOMÁTICA DO SUPABASE
-- =======================================================
-- Copie todo este código e cole no "SQL Editor" do Supabase e clique em "RUN".

-- 1. Criação da Tabela 'media'
CREATE TABLE IF NOT EXISTS public.media (
  id bigint generated by default as identity primary key,
  url text not null,
  tipo text not null,
  sort_order integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Adiciona a coluna sort_order caso a tabela já exista (sem quebrar)
ALTER TABLE public.media ADD COLUMN IF NOT EXISTS sort_order integer default 0;

ALTER TABLE public.media ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Leitura Publica Media" ON public.media;
DROP POLICY IF EXISTS "Upload Anonimo Media" ON public.media;
DROP POLICY IF EXISTS "Delete Anonimo Media" ON public.media;
DROP POLICY IF EXISTS "Update Anonimo Media" ON public.media;

CREATE POLICY "Leitura Publica Media" ON public.media FOR SELECT USING (true);
CREATE POLICY "Admin Insert Media" ON public.media FOR INSERT WITH CHECK (auth.uid() IS NOT NULL);
CREATE POLICY "Admin Delete Media" ON public.media FOR DELETE USING (auth.uid() IS NOT NULL);
CREATE POLICY "Admin Update Media" ON public.media FOR UPDATE USING (auth.uid() IS NOT NULL);

-- 2. Criação da "Pasta" (Bucket)
INSERT INTO storage.buckets (id, name, public) 
VALUES ('arquivos_vip', 'arquivos_vip', true)
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS "Leitura Publica Storage" ON storage.objects;
DROP POLICY IF EXISTS "Upload Publico Storage" ON storage.objects;
DROP POLICY IF EXISTS "Delete Publico Storage" ON storage.objects;

CREATE POLICY "Leitura Publica Storage" ON storage.objects FOR SELECT USING (bucket_id = 'arquivos_vip');
CREATE POLICY "Admin Upload Storage" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'arquivos_vip' AND auth.uid() IS NOT NULL);
CREATE POLICY "Admin Delete Storage" ON storage.objects FOR DELETE USING (bucket_id = 'arquivos_vip' AND auth.uid() IS NOT NULL);

-- =======================================================
-- 3. Criação da Tabela 'testimonials' (Feedbacks)
-- =======================================================
CREATE TABLE IF NOT EXISTS public.testimonials (
  id bigint generated by default as identity primary key,
  nome text not null,
  texto text not null,
  plano text not null,
  avatar_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

ALTER TABLE public.testimonials ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Leitura Publica Testimonials" ON public.testimonials;
DROP POLICY IF EXISTS "Upload Anonimo Testimonials" ON public.testimonials;
DROP POLICY IF EXISTS "Delete Anonimo Testimonials" ON public.testimonials;

CREATE POLICY "Leitura Publica Testimonials" ON public.testimonials FOR SELECT USING (true);
CREATE POLICY "Admin Insert Testimonials" ON public.testimonials FOR INSERT WITH CHECK (auth.uid() IS NOT NULL);
CREATE POLICY "Admin Delete Testimonials" ON public.testimonials FOR DELETE USING (auth.uid() IS NOT NULL);

-- =======================================================
-- 4. Tabela de Configurações do Site
-- =======================================================
CREATE TABLE IF NOT EXISTS public.settings (
  key text primary key,
  value text not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Leitura Publica Settings" ON public.settings;
DROP POLICY IF EXISTS "Update Anonimo Settings" ON public.settings;
DROP POLICY IF EXISTS "Insert Anonimo Settings" ON public.settings;

CREATE POLICY "Leitura Publica Settings" ON public.settings FOR SELECT USING (true);
CREATE POLICY "Admin Insert Settings" ON public.settings FOR INSERT WITH CHECK (auth.uid() IS NOT NULL);
CREATE POLICY "Admin Update Settings" ON public.settings FOR UPDATE USING (auth.uid() IS NOT NULL);

-- Valor padrão: popup desativado
INSERT INTO public.settings (key, value) VALUES ('prize_popup_enabled', 'false') ON CONFLICT (key) DO NOTHING;
